name: Build Project

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Build with PS4 Payload SDK
        uses: Scene-Collective/ps4-payload-sdk@main
        with:
          app_path: .
          build_command: sh build.sh
      - name: Upload payload artifact
        uses: actions/upload-artifact@v4
        with:
          name: hen.bin
          path: hen.bin
