---
name: "Sanity Check"

on:
  workflow_dispatch:
  push:
  pull_request:

jobs:
  build:
    if: github.ref_type != 'tag'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build with PS4 Payload SDK
        uses: Scene-Collective/ps4-payload-sdk@main
        with:
          app_path: .
          build_command: sh build.sh
      - name: Upload payload artifact
        uses: actions/upload-artifact@v4
        with:
          name: hen.bin
          path: hen.bin
